// <auto-generated />
using System;
using Comission.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Comission.Migrations
{
    [DbContext(typeof(ComissionContext))]
    [Migration("20220427201113_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Comission.Models.Piece", b =>
                {
                    b.Property<int>("PieceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Abstract")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Colorful")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Cubic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Dark")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Enamel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Impressionist")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Latex")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Light")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Modern")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OilBased")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PieceName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Watercolor")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("PieceId");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("Comission.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("isArtist")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Comission.Models.UserArtConnection", b =>
                {
                    b.Property<int>("UserArtConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PieceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserArtConnectionId");

                    b.HasIndex("PieceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserArtConnection");
                });

            modelBuilder.Entity("Comission.Models.UserArtConnection", b =>
                {
                    b.HasOne("Comission.Models.Piece", "Piece")
                        .WithMany("ArtHasUsers")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comission.Models.User", "User")
                        .WithMany("UserHasArt")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
